apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
  labels:
    app: simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation
  template:
    metadata:
      labels:
        app: simulation
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "simulation"
    spec:
      containers:
      - name: simulation
        image: dapr-trafficcontrol/simulation:1.0