apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store-file
  namespace: dapr-trafficcontrol
spec:
  type: secretstores.local.file
  metadata:
  - name: secretsFile
    value: ../dapr/components/secrets.json